name: things_to_study

on:
  push:
    branches:
      - DEV-*
      - dev-*

jobs:
  verify-flutter:
    uses: ./.github/workflows/flutter_package.yaml
    with:
      flutter_channel: 'stable'
      flutter_version: '3.19.5'
      min_coverage: 0 
      runs_on: ubuntu-latest

  verify-semantics-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    needs:
      - verify-flutter
      - verify-semantics-pull-request
    runs-on: ubuntu-latest

    steps:
      - name: noop
        run: echo 'noop'